# Generated by Django 4.2.16 on 2026-04-20 06:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(default='SAGE200', max_length=50)),
                ('sage_invoice_id', models.CharField(help_text='Sage 200 internal invoice ID (SLPostedCustomerTrans.ID)', max_length=100)),
                ('sage_invoice_number', models.CharField(help_text='Invoice number visible in Sage 200', max_length=100)),
                ('sage_account_ref', models.CharField(help_text='Customer account reference in Sage 200', max_length=50)),
                ('invoice_type', models.CharField(choices=[('B2B', 'Business to Business'), ('B2C', 'Business to Consumer'), ('B2G', 'Business to Government')], default='B2B', max_length=3)),
                ('document_type', models.CharField(choices=[('380', 'Commercial Invoice'), ('381', 'Credit Note'), ('383', 'Debit Note')], default='380', max_length=3)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency_code', models.CharField(default='NGN', max_length=3)),
                ('supplier_tin', models.CharField(max_length=50)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_address', models.TextField()),
                ('buyer_tin', models.CharField(blank=True, help_text='Required for B2B — validate before submission', max_length=50)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_address', models.TextField()),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Total before VAT (NGN)', max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=2, help_text='Total VAT (NGN)', max_digits=18)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total payable including VAT', max_digits=18)),
                ('original_currency', models.CharField(blank=True, help_text='Original currency if not NGN', max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending — waiting to be submitted to FIRS'), ('SUBMITTING', 'Submitting — currently being sent to FIRS'), ('CLEARED', 'Cleared — FIRS approved, IRN issued'), ('REJECTED', 'Rejected — FIRS rejected, see error detail'), ('FAILED', 'Failed — submission error, will retry'), ('CANCELLED', 'Cancelled — invoice cancelled in Sage 200'), ('WRITTEN_BACK', 'Complete — IRN written back to Sage 200')], db_index=True, default='PENDING', max_length=20)),
                ('ubl_payload', models.JSONField(blank=True, help_text='Full UBL JSON payload sent to FIRS', null=True)),
                ('firs_response', models.JSONField(blank=True, help_text='Raw response from FIRS API', null=True)),
                ('submission_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('irn', models.CharField(blank=True, db_index=True, help_text='Invoice Reference Number from FIRS', max_length=255)),
                ('csid', models.CharField(blank=True, help_text='Cryptographic Stamp Identifier', max_length=500)),
                ('qr_code', models.TextField(blank=True, help_text='QR code data for B2C invoices')),
                ('cleared_at', models.DateTimeField(blank=True, help_text='When FIRS cleared the invoice', null=True)),
                ('written_back_at', models.DateTimeField(blank=True, help_text='When IRN was written back to Sage 200', null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.clientcompany')),
                ('original_invoice', models.ForeignKey(blank=True, help_text='For credit/debit notes — points to original cleared invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('endpoint', models.CharField(max_length=255)),
                ('request_payload', models.JSONField()),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('duration_ms', models.IntegerField(blank=True, help_text='API call duration in milliseconds', null=True)),
                ('error', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerTINMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sage_account_ref', models.CharField(help_text='Customer account reference in Sage 200', max_length=50)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_tin', models.CharField(help_text='FIRS TIN for this buyer', max_length=50)),
                ('is_validated', models.BooleanField(default=False, help_text='True once validated against FIRS TIN API')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_mappings', to='core.clientcompany')),
            ],
            options={
                'verbose_name': 'Buyer TIN Mapping',
                'verbose_name_plural': 'Buyer TIN Mappings',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_code', models.CharField(default='EA', help_text='UN/ECE unit code', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('line_net_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=7.5, max_digits=6)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_category', models.CharField(default='S', help_text='S=Standard, Z=Zero, E=Exempt', max_length=5)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice')),
            ],
            options={
                'ordering': ['line_number'],
                'unique_together': {('invoice', 'line_number')},
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='invoices_in_client__d0ba52_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'invoice_date'], name='invoices_in_client__d454a4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['irn'], name='invoices_in_irn_ebdbe4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['next_retry_at'], name='invoices_in_next_re_1fcd35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('client', 'sage_invoice_id')},
        ),
        migrations.AlterUniqueTogether(
            name='buyertinmapping',
            unique_together={('client', 'sage_account_ref')},
        ),
    ]
