# Generated by Django 4.2.16 on 2026-04-20 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tin', models.CharField(help_text='FIRS Tax Identification Number', max_length=50, unique=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('mssql_server', models.CharField(help_text='SQL Server instance name e.g. SERVER\\SQLEXPRESS', max_length=255)),
                ('mssql_database', models.CharField(help_text='Sage 200 database name from .bak restore', max_length=255)),
                ('mssql_driver', models.CharField(default='ODBC Driver 17 for SQL Server', max_length=100)),
                ('mssql_trusted', models.BooleanField(default=True, help_text='True = Windows Authentication')),
                ('mssql_username', models.CharField(blank=True, max_length=100)),
                ('mssql_password', models.CharField(blank=True, max_length=255)),
                ('firs_api_key', models.CharField(blank=True, max_length=255)),
                ('firs_secret_key', models.CharField(blank=True, max_length=255)),
                ('sage_client_id', models.CharField(blank=True, max_length=255)),
                ('sage_client_secret', models.CharField(blank=True, max_length=255)),
                ('sage_site_id', models.CharField(blank=True, max_length=100)),
                ('sage_company_id', models.CharField(blank=True, max_length=100)),
                ('sage_api_base_url', models.URLField(blank=True)),
                ('sage_access_token', models.TextField(blank=True)),
                ('sage_refresh_token', models.TextField(blank=True)),
                ('sage_token_expires', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client Company',
                'verbose_name_plural': 'Client Companies',
                'ordering': ['name'],
            },
        ),
    ]
