# Generated by Django 4.2.16 on 2026-05-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcompany',
            name='sage300_api_company',
            field=models.CharField(blank=True, help_text='Sage 300 company code e.g. SAMLTD', max_length=20),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='sage300_api_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='sage300_api_server',
            field=models.CharField(blank=True, help_text='Sage 300 Web API server e.g. myserver.local', max_length=255),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='sage300_api_username',
            field=models.CharField(blank=True, default='ADMIN', max_length=100),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='sage300_api_version',
            field=models.CharField(blank=True, default='v1.0', max_length=10),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='sage300_mssql_database',
            field=models.CharField(blank=True, help_text='Sage 300 company database code e.g. SAMLTD', max_length=255),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='sage300_mssql_driver',
            field=models.CharField(blank=True, default='ODBC Driver 17 for SQL Server', max_length=100),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='sage300_mssql_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='sage300_mssql_server',
            field=models.CharField(blank=True, help_text='Sage 300 SQL Server instance e.g. localhost or SERVER\\\\INSTANCE', max_length=255),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='sage300_mssql_trusted',
            field=models.BooleanField(default=True, help_text='True = Windows Authentication (recommended)'),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='sage300_mssql_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
