# Generated by Django 4.2.16 on 2026-05-05 07:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_clientcompany_sage300_api_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderWatchConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('watch_path', models.CharField(help_text='Full path to watch folder e.g. C:\\InvoiceDropbox\\ or /home/invoices/', max_length=500)),
                ('processed_path', models.CharField(blank=True, help_text='Where to move processed files e.g. C:\\InvoiceDropbox\\Processed\\', max_length=500)),
                ('failed_path', models.CharField(blank=True, help_text='Where to move failed files', max_length=500)),
                ('poll_interval', models.IntegerField(default=30, help_text='How often to check folder in seconds')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_watches', to='core.clientcompany')),
            ],
            options={
                'verbose_name': 'Folder Watch Config',
            },
        ),
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('FOLDER', 'Folder Watch (auto-pickup)'), ('EMAIL', 'Email Ingestion (attachment)'), ('UPLOAD', 'Web Upload Portal (browser)')], help_text='How this file was received', max_length=10)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received — file received, not yet parsed'), ('PARSING', 'Parsing — reading Excel rows'), ('PARSED', 'Parsed — rows extracted, ready to submit'), ('PROCESSING', 'Processing — submitting to FIRS'), ('COMPLETE', 'Complete — all invoices cleared'), ('PARTIAL', 'Partial — some invoices failed'), ('FAILED', 'Failed — parsing or submission error')], db_index=True, default='RECEIVED', max_length=15)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, help_text='Path on server where the file is stored', max_length=500)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, help_text='SHA256 hash — prevents duplicate processing', max_length=64)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('email_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('total_rows', models.IntegerField(default=0, help_text='Total invoice rows found')),
                ('valid_rows', models.IntegerField(default=0)),
                ('invalid_rows', models.IntegerField(default=0)),
                ('cleared_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('parse_error', models.TextField(blank=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('uploaded_by_user', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excel_uploads', to='core.clientcompany')),
            ],
            options={
                'verbose_name': 'Excel Upload',
                'verbose_name_plural': 'Excel Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.IntegerField(help_text='Row number in the Excel file')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid — ready to submit'), ('INVALID', 'Invalid — validation error'), ('SUBMITTED', 'Submitted to FIRS'), ('CLEARED', 'Cleared — IRN received'), ('FAILED', 'Failed — submission error')], db_index=True, default='PENDING', max_length=15)),
                ('raw_data', models.JSONField(help_text='Raw column values extracted from the Excel row')),
                ('mapped_data', models.JSONField(blank=True, help_text='Mapped FIRS UBL fields ready for submission', null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('buyer_tin', models.CharField(blank=True, max_length=50)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('irn', models.CharField(blank=True, db_index=True, max_length=255)),
                ('csid', models.CharField(blank=True, max_length=500)),
                ('qr_code', models.TextField(blank=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('validation_errors', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
                ('submission_attempts', models.PositiveSmallIntegerField(default=0)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='excel_intake.excelupload')),
            ],
            options={
                'verbose_name': 'Excel Invoice Row',
                'verbose_name_plural': 'Excel Invoice Rows',
                'ordering': ['upload', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='EmailIngestConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('email_address', models.EmailField(help_text='The inbox to monitor e.g. invoices@linkoptions.com', max_length=254)),
                ('email_password', models.CharField(help_text='App password (not account password)', max_length=255)),
                ('inbox_folder', models.CharField(default='INBOX', max_length=100)),
                ('processed_folder', models.CharField(default='Processed', help_text='IMAP folder to move processed emails to', max_length=100)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_uid', models.CharField(blank=True, help_text='Last processed email UID — prevents reprocessing', max_length=50)),
                ('client', models.ForeignKey(blank=True, help_text='Leave blank for shared Link Options inbox', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_configs', to='core.clientcompany')),
            ],
            options={
                'verbose_name': 'Email Ingest Config',
            },
        ),
        migrations.AddIndex(
            model_name='excelupload',
            index=models.Index(fields=['client', 'status'], name='excel_intak_client__46bf71_idx'),
        ),
        migrations.AddIndex(
            model_name='excelupload',
            index=models.Index(fields=['file_hash'], name='excel_intak_file_ha_1c257a_idx'),
        ),
        migrations.AddIndex(
            model_name='excelupload',
            index=models.Index(fields=['method', 'status'], name='excel_intak_method_3497bc_idx'),
        ),
        migrations.AddIndex(
            model_name='excelinvoice',
            index=models.Index(fields=['status'], name='excel_intak_status_e7c81f_idx'),
        ),
        migrations.AddIndex(
            model_name='excelinvoice',
            index=models.Index(fields=['irn'], name='excel_intak_irn_c9bc79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='excelinvoice',
            unique_together={('upload', 'row_number')},
        ),
    ]
